name: Build App

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build App
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - if: startsWith(matrix.os, 'ubuntu')
        name: Build Linux App
        run: |
          sudo apt-get install -y rpm
          npx nextron build --linux --x64 --arm64

      - if: startsWith(matrix.os, 'windows')
        name: Build Windows App
        run: npx nextron build --win --x64 --arm64

      - if: startsWith(matrix.os, 'macos')
        name: Build macOS App
        run: npx nextron build --mac --x64 --universal

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            dist
            !dist/linux-unpacked
