name: Build App

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write # for creating release draft

jobs:
  build:
    name: Build App
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - if: startsWith(matrix.os, 'ubuntu')
        name: Build Linux App
        run: |
          sudo apt-get install -y rpm
          sudo snap install snapcraft --classic
          npx nextron build --linux --x64

      - if: startsWith(matrix.os, 'windows')
        name: Build Windows App
        run: npx nextron build --win --x64 --arm64

      - if: startsWith(matrix.os, 'macos')
        name: Build macOS App
        run: npx nextron build --mac --x64 --universal

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist/*.*

  # After build and archive artifacts, create a draft release with artifacts
  draft-release:
    needs: build # Wait for build job to finish & artifacts to be available
    runs-on: ubuntu-latest
    steps:
      - name: Fetch saved artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create/Update draft release & attach artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.AppImage
            dist/**/*.snap
            dist/**/*.deb
            dist/**/*.rpm
            dist/**/*.zip
            dist/**/*.tar.gz
            dist/**/*.blockmap
